// Code generated by govalid; DO NOT EDIT.
package main

import (
	"errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilPerson is returned when the Person is nil.
	ErrNilPerson = errors.New("input Person is nil")

	// ErrPersonNameRequiredValidation is returned when the PersonName is required but not provided.
	ErrPersonNameRequiredValidation = errors.New("field PersonName is required")

	// ErrPersonEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrPersonEmailEmailValidation = errors.New("field PersonEmail must be a valid email address")
)

func ValidatePerson(t *Person) error {
	if t == nil {
		return ErrNilPerson
	}

	if t.Name == "" {
		return ErrPersonNameRequiredValidation
	}

	if !validationhelper.IsValidEmail(t.Email) {
		return ErrPersonEmailEmailValidation
	}

	return nil
}
